name: Helm
permissions: {}

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - charts/mzinga/**


jobs:

  helm:
    name: "Lint, test and update version of Helm chart."
    runs-on: [self-hosted]
    if: ${{ github.event_name != 'push' }}
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 0
      - uses: azure/setup-helm@v4.3.1
        id: install-helm
      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.8.0
      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed="$(ct list-changed --config .github/workflows/chart-testing/ct.yaml)"
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi
      - name: Setup .NET
        id: setup-dotnet
        uses: actions/setup-dotnet@v5
        if: steps.list-changed.outputs.changed == 'true'
        with:
          dotnet-version: '8.0.x'

      - uses: gittools/actions/gitversion/setup@v1
        id: install-gitversion
        if: steps.list-changed.outputs.changed == 'true'
        with:
          versionSpec: '5.x'
      - id: gitversion
        uses: gittools/actions/gitversion/execute@v1
        if: steps.list-changed.outputs.changed == 'true'
      - if: steps.list-changed.outputs.changed == 'true'
        run: yq e -i '.version = "${{ steps.gitversion.outputs.MajorMinorPatch }}"' charts/mzinga/Chart.yaml
      - name: install helm unittest plugin
        if: steps.list-changed.outputs.changed == 'true'
        run: helm plugin install https://github.com/helm-unittest/helm-unittest.git --version 1.0.1

      - name: Run chart-testing (lint)
        run: ct lint --config .github/workflows/chart-testing/ct.yaml

      - name: Run Helm unit tests
        id: helm-unit-tests
        if: steps.list-changed.outputs.changed == 'true'
        run: helm unittest -f "charts/mzinga/unittests/**/*_test.yaml" charts/mzinga
  tag:
    name: Push Git Tag
    runs-on: [self-hosted]
    if: ${{ github.event_name != 'pull_request' && github.actor != 'actions-user'}}
    permissions:
      contents: write
    outputs:
      version: ${{ steps.gitversion.outputs.MajorMinorPatch }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Setup .NET
        id: setup-dotnet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '8.0.x'

      - uses: gittools/actions/gitversion/setup@v1
        id: install-gitversion
        with:
          versionSpec: '5.x'
      - id: gitversion
        uses: gittools/actions/gitversion/execute@v1

      - name: Set up Git user
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Push Git tag
        run: |
          VERSION=mzinga-${{ steps.gitversion.outputs.MajorMinorPatch }}
          git tag $VERSION
          git push origin $VERSION

  release:
    name: "Generate release for Helm chart."
    needs:
      - tag
    permissions:
      contents: write
    runs-on: [self-hosted]
    if: ${{ github.event_name != 'pull_request' && needs.tag.result == 'success'}}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "renovate[bot]"
          git config user.email "29139614+renovate[bot]@users.noreply.github.com"

      - run: yq e -i '.version = "${{ needs.tag.outputs.version }}"' charts/mzinga/Chart.yaml
      - name: Push updated Chart
        run: |
          CURRENT_BRANCH=${{ github.ref }}
          git add charts/mzinga/Chart.yaml
          git commit --no-verify -m "chore(deps): update Chart.yaml version to ${{ needs.tag.outputs.version }}."
          git push --set-upstream origin ${CURRENT_BRANCH#refs/}

      - name: Update Helm chart docs
        id: update-docs
        uses: losisin/helm-docs-github-action@v1.6.2
        with:
          chart-search-root: "charts/mzinga"
          sort-values-order: "file"
          git-push-user-name: "renovate[bot]"
          git-push-user-email: "29139614+renovate[bot]@users.noreply.github.com"
          git-commit-message: "docs(mzinga): update mzinga helm chart documentation."
          git-push: true

      - name: Install Helm
        uses: azure/setup-helm@v4.3.1

      - name: Add Helm dependency repos
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo update

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_GENERATE_RELEASE_NOTES: true
